name: Docker Image CI

on:
  push:
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  TARGET: ddb-proxy

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: get-repo
      name: Get Docker Image Identifiers
      run: echo "::set-output name=IMAGE_REPOSITORY::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    
    - name: Build & Push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: docker
        target: ${{ env.TARGET }}
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm
        tags: '${{ env.REGISTRY }}/${{ steps.get-repo.outputs.IMAGE_REPOSITORY }}:${GITHUB_REF#refs/tags/v},${{ env.REGISTRY }}/${{ steps.get-repo.outputs.IMAGE_REPOSITORY }}:latest'
